var hierarchy =
[
    [ "app", "classapp.html", null ],
    [ "PidTabConfig::BackgroundConfig", "structPidTabConfig_1_1BackgroundConfig.html", null ],
    [ "BdfHeader", "structBdfHeader.html", null ],
    [ "Plot::Binding", "structPlot_1_1Binding.html", null ],
    [ "Config", "classConfig.html", null ],
    [ "ControlEvent", "structControlEvent.html", null ],
    [ "CountdownFrame", "structCountdownFrame.html", null ],
    [ "CurveParameters", "structCurveParameters.html", null ],
    [ "DataBus", "classDataBus.html", null ],
    [ "DisplayBinding", "structDisplayBinding.html", null ],
    [ "FilesMenuDeps", "structFilesMenuDeps.html", null ],
    [ "PidTabConfig::GlowPlugSwitchConfig", "structPidTabConfig_1_1GlowPlugSwitchConfig.html", null ],
    [ "GraphicTabConfig", "structGraphicTabConfig.html", null ],
    [ "GraphicTapDeps", "structGraphicTapDeps.html", null ],
    [ "Writer< MAX_FRAME_SIZE, BUFFER_SIZE >::Header", "structWriter_1_1Header.html", null ],
    [ "PidLayout::LayoutItem", "structPidLayout_1_1LayoutItem.html", null ],
    [ "Message", "classMessage.html", [
      [ "AckBB", "classAckBB.html", null ],
      [ "BBControlCommand", "classBBControlCommand.html", null ],
      [ "GlowPlugCommand", "classGlowPlugCommand.html", null ],
      [ "SensorReading", "classSensorReading.html", null ],
      [ "SequenceCommand", "classSequenceCommand.html", null ],
      [ "SequenceFileFrame", "classSequenceFileFrame.html", null ],
      [ "SetPressureCommand", "classSetPressureCommand.html", null ],
      [ "TVCTestCommand", "classTVCTestCommand.html", null ],
      [ "TestAbortionCommand", "classTestAbortionCommand.html", null ],
      [ "TestLauchConfirmation", "classTestLauchConfirmation.html", null ],
      [ "TextMessage", "classTextMessage.html", null ],
      [ "ValveCommand", "classValveCommand.html", null ],
      [ "ValveReading", "classValveReading.html", null ]
    ] ],
    [ "metaData", "structmetaData.html", null ],
    [ "OverlayDeps", "structOverlayDeps.html", null ],
    [ "ParametersWindowDeps", "structParametersWindowDeps.html", null ],
    [ "PidTabConfig", "structPidTabConfig.html", null ],
    [ "PidTabDeps", "structPidTabDeps.html", null ],
    [ "PlotConfig", "structPlotConfig.html", null ],
    [ "ProtocolCodec", "classProtocolCodec.html", null ],
    [ "QFrame", null, [
      [ "ActuatorSwitchWidget", "classActuatorSwitchWidget.html", [
        [ "GlowPlugSwitch", "classGlowPlugSwitch.html", null ],
        [ "ValveSwitch", "classValveSwitch.html", null ]
      ] ],
      [ "CountdownClock", "classCountdownClock.html", null ],
      [ "DebugDisplay", "classDebugDisplay.html", null ]
    ] ],
    [ "QLabel", null, [
      [ "Data", "classData.html", null ],
      [ "Locker", "classLocker.html", null ],
      [ "Logo", "classLogo.html", null ],
      [ "PidBackground", "classPidBackground.html", null ],
      [ "SensorValueIndicator", "classSensorValueIndicator.html", null ],
      [ "TankPressureIndicador", "classTankPressureIndicador.html", null ]
    ] ],
    [ "QLayout", null, [
      [ "PidLayout", "classPidLayout.html", null ]
    ] ],
    [ "QMainWindow", null, [
      [ "MainWindow", "classMainWindow.html", null ]
    ] ],
    [ "QMenu", null, [
      [ "ExportMenu", "classExportMenu.html", null ],
      [ "FilesMenu", "classFilesMenu.html", null ],
      [ "ToolsMenu", "classToolsMenu.html", null ]
    ] ],
    [ "QObject", null, [
      [ "ActuatorSwitchViewModel", "classActuatorSwitchViewModel.html", null ],
      [ "AppModels", "classAppModels.html", null ],
      [ "AppServices", "classAppServices.html", null ],
      [ "AppViewModel", "classAppViewModel.html", null ],
      [ "CSVLogger", "classCSVLogger.html", null ],
      [ "CountdownClockViewModel", "classCountdownClockViewModel.html", null ],
      [ "DebugDisplayViewModel", "classDebugDisplayViewModel.html", null ],
      [ "EmergencyControlsViewModel", "classEmergencyControlsViewModel.html", null ],
      [ "ExportMenuViewModel", "classExportMenuViewModel.html", null ],
      [ "FileSystem", "classFileSystem.html", null ],
      [ "InitialiseValveButtonViewModel", "classInitialiseValveButtonViewModel.html", null ],
      [ "LogTerminalViewModel", "classLogTerminalViewModel.html", null ],
      [ "Logger", "classLogger.html", null ],
      [ "PidViewModel", "classPidViewModel.html", null ],
      [ "PlotViewModel", "classPlotViewModel.html", null ],
      [ "PressureTanksModel", "classPressureTanksModel.html", null ],
      [ "SensorValueIndicatorViewModel", "classSensorValueIndicatorViewModel.html", null ],
      [ "TankPressureControlerViewModel", "classTankPressureControlerViewModel.html", null ],
      [ "TankPressureSettingsIndicatorViewModel", "classTankPressureSettingsIndicatorViewModel.html", null ],
      [ "TestBenchModel", "classTestBenchModel.html", null ],
      [ "TestLauncherViewModel", "classTestLauncherViewModel.html", null ],
      [ "Timer", "classTimer.html", null ],
      [ "TxtParser", "classTxtParser.html", null ],
      [ "UdpChannel", "classUdpChannel.html", null ],
      [ "UdpChannelParametersViewModel", "classUdpChannelParametersViewModel.html", null ],
      [ "UdpWorker", "classUdpWorker.html", null ]
    ] ],
    [ "QPushButton", null, [
      [ "InitialiseValveButton", "classInitialiseValveButton.html", null ]
    ] ],
    [ "QTableWidget", null, [
      [ "StatusTableWidget", "classStatusTableWidget.html", null ]
    ] ],
    [ "QWidget", null, [
      [ "Chrono", "classChrono.html", null ],
      [ "CloseButton", "classCloseButton.html", null ],
      [ "EmergencyControls", "classEmergencyControls.html", null ],
      [ "GraphicTab", "classGraphicTab.html", null ],
      [ "Overlay", "classOverlay.html", null ],
      [ "ParametersWindow", "classParametersWindow.html", null ],
      [ "PidTab", "classPidTab.html", null ],
      [ "Plot", "classPlot.html", null ],
      [ "TankPressureControlFrame", "classTankPressureControlFrame.html", null ],
      [ "TankPressureControler", "classTankPressureControler.html", null ],
      [ "TestLauncher", "classTestLauncher.html", null ],
      [ "TestTab", "classTestTab.html", null ],
      [ "UdpChannelParametersWidget", "classUdpChannelParametersWidget.html", null ],
      [ "actuatorControlFrame", "classactuatorControlFrame.html", null ],
      [ "logTerminalFrame", "classlogTerminalFrame.html", null ],
      [ "tvcControlFrame", "classtvcControlFrame.html", null ]
    ] ],
    [ "RingBuffer< MAX_FRAME_SIZE >", "classRingBuffer.html", null ],
    [ "SensorData", "structSensorData.html", null ],
    [ "PidTabConfig::SensorValueIndicatorConfig", "structPidTabConfig_1_1SensorValueIndicatorConfig.html", null ],
    [ "PidTabConfig::StatusTableConfig", "structPidTabConfig_1_1StatusTableConfig.html", null ],
    [ "DataBus::Subscriber", "structDataBus_1_1Subscriber.html", null ],
    [ "PidTabConfig::TankPressureIndicadorConfig", "structPidTabConfig_1_1TankPressureIndicadorConfig.html", null ],
    [ "TestBenchStatesList", "classTestBenchStatesList.html", null ],
    [ "TestTabDeps", "structTestTabDeps.html", null ],
    [ "timeRangeButton", "structtimeRangeButton.html", null ],
    [ "ToolsMenuDeps", "structToolsMenuDeps.html", null ],
    [ "TpcFrameConfig::TpcConfig", "structTpcFrameConfig_1_1TpcConfig.html", null ],
    [ "TpcDeps", "structTpcDeps.html", null ],
    [ "TpcFrameConfig", "structTpcFrameConfig.html", null ],
    [ "UdpLogger", "classUdpLogger.html", null ],
    [ "PidTabConfig::ValveSwitchConfig", "structPidTabConfig_1_1ValveSwitchConfig.html", null ],
    [ "Writer< MAX_FRAME_SIZE, BUFFER_SIZE >", "classWriter.html", null ]
];